[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.package]
version = "0.0.7"
edition = "2021"
license = "MIT"
repository = "https://github.com/rationalintelligence/crb"

[workspace.dependencies]
anyhow = "1.0.94"
async-trait = "0.1.83"
crb-core.path = "crates/crb-core"
derive_more = { version = "1.0.0", features = ["full"] }
futures = "0.3.31"
log = "0.4.22"
thiserror = "2.0.7"
tokio = "1.42.0"
