[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.package]
version = "0.0.4"
edition = "2021"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
crb-core.path = "crates/crb-core"
derive_more = "0.99.17"
futures = "0.3.30"
log = "0.4.21"
thiserror = "1.0.61"
tokio = "1.37.0"
