[package]
name = "crb-send"
description = "CRB | Composable Runtime Blocks | Send"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
