[package]
name = "crb"
description = "CRB | Composable Runtime Blocks"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crb-core.workspace = true
