[package]
name = "crb"
description = "CRB | Composable Runtime Blocks"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crb-actor.workspace = true
crb-core.workspace = true
crb-supervisor.workspace = true

[dev-dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
