[package]
name = "crb-parallel"
description = "CRB | Composable Runtime Blocks | Parallel"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
