[package]
public = false
name = "crb-example-tui-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.83"
crb.path = "../../crates/crb"
crossterm = "0.28.1"
ratatui = "0.29.0"
tokio = { version = "1.42.0", features = ["full"] }
