[package]
name = "crb-task"
description = "CRB | async actor framework | task"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
crb-core.workspace = true
futures.workspace = true
log.workspace = true
