[package]
name = "crb-routine"
description = "CRB | Composable Runtime Blocks | Routine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
